import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import GaugeChart from "react-gauge-chart";
import Donut from "../component/Donut";
import HalfDonut from "../component/HalfDonut";
import Stats from "../component/stats";

const Home: NextPage = () => {
  const [statement, setStatement] = useState("default");

  const [showStats, setShowStats] = useState(false);
  return (
    <div>
      <Head>
        <title>Stateful Profile Score Mockup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-full">
        <div className="pt-10">
          <Donut statement={statement} setStatement={setStatement} />
        </div>
        <p className="mt-10 rounded-md bg-gray-300 shadow-md w-1/2 lg:w-1/4 mx-auto p-3 text-center">
          {statement}
        </p>
        <div>
          <HalfDonut statement={statement} setStatement={setStatement} />
        </div>
        <p className="mt-10 rounded-md bg-gray-300 shadow-md w-1/2 lg:w-1/4 mx-auto p-3 text-center">
          {statement}
        </p>
      </div>
      {/* <main className="bg-white lg:px-32 xl:px-24 min-h-screen">
        <section className=" 2xl:w-3/4 mx-auto   shadow-xl min-h-screen flex flex-col items-center justify-center px-5">
          <div className="w-full lg:px-24 flex flex-col items-center justify-center h-full">
            <div className="mb-10 flex flex-row justify-around items-center h-44 p-4 border rounded-lg  shadow-xl">
              <div className=" flex items-center min-w-min shrink-0 w-16 h-16">
                <img
                  src="./ljaph-4.jpg"
                  className="self-start mr-2 rounded-full object-cover object-top w-full h-full "
                  alt="Profile Pic"
                />
              </div>

              <div className="space-y-1 px-4 flex flex-col flex-grow">
                <h2 className="text-3xl text-left">lorenzejay</h2>
                <p className="flex flex-row  text-md  font-light">
                  🔥 Coding TypeScript React on <br /> profile-score-redesign #
                  main in index.tsx
                </p>
              </div>

              {/* <div
                className={`relative hidden md:flex  items-center cursor-pointer `}
                onMouseEnter={() => setShowStats(true)}
                onMouseLeave={() => setShowStats(false)}
              >
                <GaugeChart
                  style={{ width: 150 }}
                  id="gauge-chart2"
                  nrOfLevels={10}
                  colors={["#F5CAD3", "#E98A9E", "#F62359"]}
                  arcWidth={0.2}
                  marginInPercent={0}
                  percent={0.44}
                  arcPadding={0}
                  cornerRadius={0}
                  textColor={"black"}
                  animate={false}
                />
                <div
                  className={`${
                    showStats ? "block" : "hidden"
                  } border shadow-xl rounded-lg bg-white p-2 z-10 w-60 h-44 absolute -right-10 bottom-20`}
                >
                  <div
                    className=""
                    style={{
                      position: "absolute",
                      borderLeft: "10px solid transparent",
                      borderRight: "10px solid transparent",
                      left: " 116.516px",
                      opacity: "1",
                      borderTop: "10px solid #fff",
                      bottom: "-10px",
                      background: "none",
                    }}
                  ></div>
                  <div className="">
                    <p className="">
                      <span className="font-semibold">Working Hours: </span>17
                      of 45 pts
                    </p>
                    <p className="text-sm text-gray-600">
                      {">"} Duration 3 of 8 Hours
                    </p>
                    <hr className="mt-2" />
                  </div>
                  <div className="py-2">
                    <p className="">
                      <span className="font-semibold">Coding Activity: </span>23
                      of 45 pts
                    </p>
                    <p className="text-sm text-gray-600">
                      {">"} Duration 1h 16m of 2h 30m goal
                    </p>
                    <hr className="my-2" />
                  </div>
                  <div className="">
                    <p className="">
                      <span className="font-semibold">Breaks: </span>0 of 10 pts
                    </p>
                  </div>
                </div> */}
      {/* </div> */}
      {/* </div>
          </div>
          <Stats />
        </section>
      </main> */}
    </div>
  );
};

export default Home;
